# Generated by Django 5.2.11 on 2026-04-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usuario_onboarding_nullable'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='uq_project_name_per_user_active',
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('user', 'name'), name='uq_project_name_per_user_active'),
        ),
    ]
