"""
Django settings for codemio_back project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

import dj_database_url
from decouple import Csv, config

try:
    import pymysql

    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY is required and must be set in environment variables.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    # Local apps
    'authentication',
    'projects',
    'analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codemio_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codemio_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if available (for production), otherwise fallback to SQLite for local development
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # dj-database-url 2.x no reconoce mysql+pymysql; con PyMySQL como MySQLdb basta el esquema mysql://
    if DATABASE_URL.startswith('mysql+pymysql://'):
        DATABASE_URL = 'mysql://' + DATABASE_URL.removeprefix('mysql+pymysql://')
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='',
    cast=Csv()
)

CORS_ALLOW_CREDENTIALS = True

THROTTLE_RATE_5_PER_MIN = '5/min'
THROTTLE_RATE_10_PER_MIN = '10/min'
THROTTLE_RATE_12_PER_MIN = '12/min'
THROTTLE_RATE_20_PER_MIN = '20/min'
THROTTLE_RATE_240_PER_MIN = '240/min'

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'TAGS_SORTER': 'alpha',
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': (
                '**access_token** de Cognito (respuesta `tokens.access_token` de `POST /auth/login/`). '
                'Swagger 2 / apiKey: pega en Authorize el **valor completo** de la cabecera, '
                'incluyendo la palabra Bearer y un espacio antes del JWT, por ejemplo: '
                '`Bearer eyJraWQiOiJ...` (si solo pegas el JWT, la petición fallará).'
            ),
        }
    },
}

# Django REST Framework
AUTH_RATE_LIMIT = THROTTLE_RATE_10_PER_MIN
AUTH_LOGOUT_RATE_LIMIT = THROTTLE_RATE_20_PER_MIN
ANALYSIS_RUNS_RATE_LIMIT = THROTTLE_RATE_20_PER_MIN

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_send': THROTTLE_RATE_10_PER_MIN,
        'auth_validate': THROTTLE_RATE_10_PER_MIN,
        'auth_login': THROTTLE_RATE_10_PER_MIN,
        'auth_register': THROTTLE_RATE_10_PER_MIN,
        'auth_forgot_password': THROTTLE_RATE_10_PER_MIN,
        'auth_refresh': THROTTLE_RATE_12_PER_MIN,
        'auth_logout': THROTTLE_RATE_20_PER_MIN,
        'auth_forgot_validate': THROTTLE_RATE_10_PER_MIN,
        'auth_confirm_forgot': THROTTLE_RATE_5_PER_MIN,
        'analysis_runs': THROTTLE_RATE_20_PER_MIN,
        'analysis_runs_write': THROTTLE_RATE_20_PER_MIN,
        'analysis_runs_read': THROTTLE_RATE_240_PER_MIN,
        'sonar_webhook': THROTTLE_RATE_20_PER_MIN,
    },
}

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_COGNITO_REGION = config('AWS_COGNITO_REGION', default='us-east-1')
AWS_COGNITO_USER_POOL_ID = config('AWS_COGNITO_USER_POOL_ID', default='')
AWS_COGNITO_CLIENT_ID = config('AWS_COGNITO_CLIENT_ID', default='')
AWS_COGNITO_CLIENT_SECRET = config('AWS_COGNITO_CLIENT_SECRET', default='')
AWS_COGNITO_ISSUER = config('AWS_COGNITO_ISSUER', default='')
AWS_COGNITO_DOMAIN = config('AWS_COGNITO_DOMAIN', default='')
AWS_COGNITO_OAUTH_REDIRECT_URI = config('AWS_COGNITO_OAUTH_REDIRECT_URI', default='')
AWS_COGNITO_OAUTH_LOGOUT_REDIRECT_URI = config('AWS_COGNITO_OAUTH_LOGOUT_REDIRECT_URI', default='')
AWS_COGNITO_OAUTH_SCOPES = config('AWS_COGNITO_OAUTH_SCOPES', default='openid profile email')
AWS_COGNITO_OAUTH_IDP_NAME = config('AWS_COGNITO_OAUTH_IDP_NAME', default='Auth0')
AUTH0_ISSUER = config('AUTH0_ISSUER', default='')
AUTH0_AUDIENCE = config('AUTH0_AUDIENCE', default='')
FRONTEND_DASHBOARD_URL = config('FRONTEND_DASHBOARD_URL', default='http://localhost:5173/dashboard')
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
SESSION_COOKIE_DOMAIN = config('SESSION_COOKIE_DOMAIN', default='')
SESSION_COOKIE_MAX_AGE = config('SESSION_COOKIE_MAX_AGE', default=3600, cast=int)
REFRESH_COOKIE_MAX_AGE = config('REFRESH_COOKIE_MAX_AGE', default=2592000, cast=int)
COOKIE_ACCESS_TOKEN_NAME = config('COOKIE_ACCESS_TOKEN_NAME', default='codemio_access_token')
COOKIE_REFRESH_TOKEN_NAME = config('COOKIE_REFRESH_TOKEN_NAME', default='codemio_refresh_token')
COOKIE_ID_TOKEN_NAME = config('COOKIE_ID_TOKEN_NAME', default='codemio_id_token')
SOCIAL_AUTH_DEBUG_LOGS = config('SOCIAL_AUTH_DEBUG_LOGS', default=False, cast=bool)
SOCIAL_AUTH_LOG_FULL_TOKENS = config('SOCIAL_AUTH_LOG_FULL_TOKENS', default=False, cast=bool)
SOCIAL_AUTH_LOG_FULL_CLAIMS = config('SOCIAL_AUTH_LOG_FULL_CLAIMS', default=False, cast=bool)
PROFILE_PAYLOAD_KEY_ID = config('PROFILE_PAYLOAD_KEY_ID', default='profile-v1')
PROFILE_PAYLOAD_RSA_PUBLIC_KEY_PEM = config('PROFILE_PAYLOAD_RSA_PUBLIC_KEY_PEM', default='')
PROFILE_PAYLOAD_RSA_PRIVATE_KEY_PEM = config('PROFILE_PAYLOAD_RSA_PRIVATE_KEY_PEM', default='')

ANALYSIS_MAX_UPLOAD_BYTES = config('ANALYSIS_MAX_UPLOAD_BYTES', default=10485760, cast=int)
ANALYSIS_MAX_EXTRACTED_BYTES = config('ANALYSIS_MAX_EXTRACTED_BYTES', default=31457280, cast=int)
ANALYSIS_MAX_EXTRACTED_FILES = config('ANALYSIS_MAX_EXTRACTED_FILES', default=500, cast=int)
ANALYSIS_MAX_ZIP_ENTRIES = config('ANALYSIS_MAX_ZIP_ENTRIES', default=2000, cast=int)
ANALYSIS_MAX_ZIP_PATH_DEPTH = config('ANALYSIS_MAX_ZIP_PATH_DEPTH', default=12, cast=int)
ANALYSIS_MAX_ZIP_COMPRESSION_RATIO = config('ANALYSIS_MAX_ZIP_COMPRESSION_RATIO', default=100.0, cast=float)
ANALYSIS_MAX_ZIP_ENTRY_BYTES = config('ANALYSIS_MAX_ZIP_ENTRY_BYTES', default=31457280, cast=int)
ANALYSIS_MAX_INFLIGHT_TASKS = config('ANALYSIS_MAX_INFLIGHT_TASKS', default=50, cast=int)
ANALYSIS_RETRY_ATTEMPTS = config('ANALYSIS_RETRY_ATTEMPTS', default=2, cast=int)
ANALYSIS_RETRY_BACKOFF_SECONDS = config('ANALYSIS_RETRY_BACKOFF_SECONDS', default=1.5, cast=float)
ANALYSIS_TOOL_TIMEOUT_SECONDS = config('ANALYSIS_TOOL_TIMEOUT_SECONDS', default=120, cast=int)
ANALYSIS_WORKERS = config('ANALYSIS_WORKERS', default=2, cast=int)
ANALYSIS_PMD_COMMAND = config('ANALYSIS_PMD_COMMAND', default='pmd')
ANALYSIS_PMD_RULESETS = config(
    'ANALYSIS_PMD_RULESETS',
    default='category/java/bestpractices.xml,category/java/errorprone.xml,category/java/design.xml',
)
ANALYSIS_SPOTBUGS_COMMAND = config('ANALYSIS_SPOTBUGS_COMMAND', default='spotbugs')
ANALYSIS_SEMGREP_COMMAND = config('ANALYSIS_SEMGREP_COMMAND', default='semgrep')
ANALYSIS_GATE_MAX_SECURITY_RATING = config('ANALYSIS_GATE_MAX_SECURITY_RATING', default=1, cast=int)
ANALYSIS_GATE_MAX_RELIABILITY_RATING = config('ANALYSIS_GATE_MAX_RELIABILITY_RATING', default=1, cast=int)
ANALYSIS_GATE_MAX_MAINTAINABILITY_RATING = config('ANALYSIS_GATE_MAX_MAINTAINABILITY_RATING', default=2, cast=int)
ANALYSIS_GATE_WARN_CODE_SMELLS_THRESHOLD = config('ANALYSIS_GATE_WARN_CODE_SMELLS_THRESHOLD', default=20, cast=int)
ANALYSIS_GATE_WARN_MIN_COVERAGE = config('ANALYSIS_GATE_WARN_MIN_COVERAGE', default=60.0, cast=float)

SONAR_HOST_URL = config('SONAR_HOST_URL', default='https://sonarcloud.io')
SONAR_TOKEN = config('SONAR_TOKEN', default='')
SONAR_ORGANIZATION = config('SONAR_ORGANIZATION', default='')
SONAR_SCANNER_COMMAND = config('SONAR_SCANNER_COMMAND', default='sonar-scanner')
SONAR_RUNTIME_PROJECT_PREFIX = config('SONAR_RUNTIME_PROJECT_PREFIX', default='codemio-runtime')
SONAR_QUALITYGATE_TIMEOUT_SECONDS = config('SONAR_QUALITYGATE_TIMEOUT_SECONDS', default=180, cast=int)
SONAR_API_TIMEOUT_SECONDS = config('SONAR_API_TIMEOUT_SECONDS', default=30, cast=int)
SONAR_WEBHOOK_SECRET = config('SONAR_WEBHOOK_SECRET', default='')
SONAR_WEBHOOK_STALE_MINUTES = config('SONAR_WEBHOOK_STALE_MINUTES', default=45, cast=int)
DEBUG_ANALYSIS_INSTRUMENTATION = config('DEBUG_ANALYSIS_INSTRUMENTATION', default=False, cast=bool)
