# Generated by Django 5.2.11 on 2026-04-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_usuario_onboarding_nullable'),
        ('projects', '0002_remove_project_uq_project_name_per_user_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=20)),
                ('input_type', models.CharField(choices=[('java', 'Java'), ('zip', 'Zip')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('total_files_analyzed', models.PositiveIntegerField(default=0)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, default='', max_length=255)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='authentication.usuario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(db_index=True, max_length=30)),
                ('severity', models.CharField(db_index=True, max_length=20)),
                ('rule', models.CharField(blank=True, default='', max_length=180)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analysis.analysisrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['project', 'status'], name='analysis_an_project_5ec63f_idx'),
        ),
    ]
