# Generated by Django 5.2.11 on 2026-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfinding',
            name='message_es',
            field=models.TextField(blank=True, default=''),
        ),
    ]
