# Generated by Django 5.2.11 on 2026-04-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisfinding_message_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfinding',
            name='effort_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfinding',
            name='finding_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='bugs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='code_smells',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='complexity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='coverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='duplicated_lines_density',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='ncloc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='quality_gate_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='sonar_project_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='vulnerabilities',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
