# Generated by Django 5.2.11 on 2026-04-17 13:01

from pathlib import PurePosixPath
from django.db import migrations, models


def _normalize_logical_filename(raw_name: str) -> str:
    normalized = str(raw_name or '').replace('\\', '/').strip()
    return PurePosixPath(normalized).name.lower()


def _backfill_logical_filename_and_active_state(apps, schema_editor):
    AnalysisRun = apps.get_model('analysis', 'AnalysisRun')
    runs = list(
        AnalysisRun.objects.all()
        .order_by('project_id', 'id')
        .only('id', 'project_id', 'original_filename')
    )

    latest_run_by_key = {}
    for run in runs:
        logical_filename = _normalize_logical_filename(run.original_filename)
        key = (run.project_id, logical_filename)
        latest_run_by_key[key] = run.id

    for run in runs:
        logical_filename = _normalize_logical_filename(run.original_filename)
        key = (run.project_id, logical_filename)
        AnalysisRun.objects.filter(pk=run.id).update(
            logical_filename=logical_filename,
            is_active_for_filename=(run.id == latest_run_by_key[key]),
        )


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysisfinding_analysis_an_run_id_a3331e_idx_and_more'),
        ('authentication', '0003_usuario_onboarding_nullable'),
        ('projects', '0002_remove_project_uq_project_name_per_user_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='is_active_for_filename',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='logical_filename',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.RunPython(
            _backfill_logical_filename_and_active_state,
            _noop_reverse,
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_for_filename', True), models.Q(('logical_filename', ''), _negated=True)), fields=('project', 'logical_filename'), name='analysis_unique_active_logical_file_per_project'),
        ),
    ]
