# Generated by Django 5.2.11 on 2026-04-17 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysisrun_is_active_for_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='classes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='inheritance_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='interclass_calls_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='methods_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='parameters_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnalysisFileMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=500)),
                ('classes_count', models.PositiveIntegerField(default=0)),
                ('methods_count', models.PositiveIntegerField(default=0)),
                ('parameters_count', models.PositiveIntegerField(default=0)),
                ('inheritance_count', models.PositiveIntegerField(default=0)),
                ('interclass_calls_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='file_metrics', to='analysis.analysisrun')),
            ],
            options={
                'ordering': ['file_path', 'id'],
                'indexes': [models.Index(fields=['run', 'file_path'], name='analysis_an_run_id_ba91a1_idx')],
            },
        ),
    ]
